# Gradient descent

## Batch GD
p. 115 of hands on machine learning with scikit-learn and tensorflow

In [1]:
import numpy as np

In [5]:
X = 2 * np.random.rand(100, 1) # 100 x 1 array
y = 4 + 3 * X + np.random.rand(100, 1) # linear equation

I think 4 = constant and np.random.rand is the residual error. Should probably double check this somewhere...

In [15]:
# Create array with x0 for constant
X_b = np.c_[np.ones(shape=(100, 1)), X] # add x0 = 1 to each instance

In [16]:
# Can see transposed:
X_b.T

array([[1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.  

In [19]:
eta = 0.1 # learning rate
n_iterations = 1000
m = 100 # How many rows/observations

theta = np.random.randn(2, 1) # random initialisation 2x1 array

for iteration in range(n_iterations):
    gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
    theta = theta - eta * gradients

In [20]:
theta

array([[4.47690812],
       [3.01923756]])

In [21]:
# Normal equation - p.109
theta_best = np.linalg.inv(X_b.T.dot(X_b)).dot(X_b.T).dot(y)
theta_best

array([[4.47690812],
       [3.01923756]])

Can see the gradient batch descent method (iterative), gets same param results as normal equation.

### What happens if I change m
m is number of instance/observations/rows of dataset (could be training or test, depending on what I'm modelling on).

Actually I shouldn't really be changing the m, since this was set earlier when I created the data set with array 100 x 1.

Oh well, fun to experiment.

In [26]:
eta = 0.1 # learning rate
n_iterations = 1000
m = 100000

theta = np.random.randn(2, 1) # random initialisation 2x1 array

for iteration in range(n_iterations):
    gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
    theta = theta - eta * gradients
    
theta

array([[0.60354508],
       [1.20854741]])

### Change learning rate

In [29]:
eta = 0.5 # learning rate
n_iterations = 1000
m = 100

theta = np.random.randn(2, 1) # random initialisation 2x1 array

for iteration in range(n_iterations):
    gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
    theta = theta - eta * gradients
    
theta

array([[-1.62936189e+127],
       [-2.04212899e+127]])

### Change iterations

In [30]:
eta = 0.1 # learning rate
n_iterations = 10
m = 100

theta = np.random.randn(2, 1) # random initialisation 2x1 array

for iteration in range(n_iterations):
    gradients = 2/m * X_b.T.dot(X_b.dot(theta) - y)
    theta = theta - eta * gradients
    
theta

array([[3.63908813],
       [3.67551297]])

## SGD
p.118

In [36]:
m = 100 # sample size
n_epochs = 50
t0, t1 = 5, 50 # learning schedule hyperparameters

def learning_schedule(t):
    return t0 / (t + t1)

theta = np.random.randn(2, 1) # random initialisation

for epoch in range(n_epochs):
    for i in range(m):
        random_index = np.random.randint(m)
        xi = X_b[random_index:random_index+1] # select one random instance
        yi = y[random_index:random_index+1]
        gradients = 2 * xi.T.dot(xi.dot(theta) - yi)
        eta = learning_schedule(epoch * m + i)
        theta = theta - eta * gradients
        
theta

array([[4.48495165],
       [3.03213169]])

Random thought - if `X_b[81]` is the same as `X_b[81:82]` then why can't I just shorten the code to `X_b[random_index]`?